local fzf = require("fzf-lua")
fzf.setup({})
vim.cmd("FzfLua register_ui_select")

vim.keymap.set('n', '<leader>ff', fzf.files, {})
vim.keymap.set('n', '<leader>fg', fzf.live_grep, {})
vim.keymap.set('n', '<leader>fl', fzf.blines, {})
vim.keymap.set('n', '<leader>fc', fzf.command_history, {})
vim.keymap.set('n', '<leader>fC', fzf.commands, {})
vim.keymap.set('n', '<leader>fs', fzf.search_history, {})
vim.keymap.set('n', '<leader>fm', fzf.marks, {})
vim.keymap.set('n', '<leader>fd', fzf.diagnostics_document, {})
vim.keymap.set('n', '<leader>fD', fzf.diagnostics_workspace, {})
vim.keymap.set('n', '<leader>fk', fzf.keymaps, {})
vim.keymap.set('n', '<leader>fb', fzf.buffers, {})
vim.keymap.set('n', '<leader>fo', fzf.oldfiles, {})
vim.keymap.set('n', '<leader>fq', fzf.quickfix, {})
vim.keymap.set('n', '<leader>fj', fzf.jumps, {})
vim.keymap.set('n', '<leader>fr', fzf.registers, {})
vim.keymap.set('n', '<leader>fa', fzf.builtin, {})
